version: "3.8"


services:

  nginx:
    build:
      context: deploy/nginx
    image: kimetrics-nginx:latest
    ports:
      - 8080:80
    environment:
      - NGINX_PORT=80
      - APP_HOST=django
      - APP_PORT=9999
      - STATIC_URL=/static/
      - STATIC_ROOT=/app/pos/staticfiles/
    depends_on:
      - django

  django:
    build:
      context: .
    image: kimetrics-app:latest
    environment:
      - DJANGO_MIGRATE=True
      - APP_PORT=9999
      - DB_NAME=test
      - DB_USER=test
      - DB_PASS=test
      - DB_HOST=db
      - DB_PORT=5432
      - DEBUG=True
    volumes:
      - ./src:/app
    depends_on:
      - db

  db:
    image: postgres:12.0-alpine
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=test
      - POSTGRES_PASSWORD=test
      - POSTGRES_DB=test


