version: "3.8"

services:

  nginx:
    build:
      context: deploy/nginx
    image: kimetrics-nginx:latest
    ports:
      - 8080:80
    environment:
      - NGINX_PORT=80
    depends_on:
      - django

  django:
    build:
      context: .
    image: kimetrics-app:latest
    environment:
      - DATABASE_URL=postgres://test:test@db:5432/test
      - DEBUG=True
    ports:
      - "8000:8000"
    volumes:
      - ./src:/app
    depends_on:
      - db

  db:
    image: postgres:12.0-alpine
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=test
      - POSTGRES_PASSWORD=test
      - POSTGRES_DB=test


