# Generated by Django 3.1.13 on 2021-11-30 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=250)),
                ('unit_price', models.FloatField()),
                ('stock', models.IntegerField()),
            ],
        ),
    ]
