name: Python application

on:
  push:
    branches: [ features ]
  pull_request:
    branches: [ features ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8.5
      uses: actions/setup-python@v2
      with:
        python-version: 3.8.5
    - name: Install dependencies
      run: |
        apt-get install postgresql
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Running tests
      run: |
        cd src
        python manage.py test
    - name: Lint with flake8
      run: |
        flake8
