name: Python application

on:
  push:
    branches:
      - features
  pull_request:
    branches:
      - main

jobs:

  test:
    name: Testing
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:12.0-alpine
        env:
          POSTGRES_USER: test
          POSTGRES_PASSWORD: test
          POSTGRES_DB: test
        ports:
          - "5432:5432"

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python 3.8.5
      uses: actions/setup-python@v2
      with:
        python-version: 3.8.5

    - name: Install python dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

    - name: Running django tests
      run: |
        cd src
        python manage.py test
      env:
        DB_NAME: test
        DB_USER: test
        DB_PASS: test
        DB_HOST: 127.0.0.1
        DB_PORT: 5432

    - name: Lint with flake8
      run: |
        cd src
        flake8

  docker-build:
    needs: [test]
    name: Docker build
    runs-on: ubuntu-latest
    steps:
    - name: Check out the repo
      uses: actions/checkout@v2

    - name: Docker meta
      id: docker_meta
      uses: crazy-max/ghaction-docker-meta@v1
      with:
        images: app/name # list of Docker images to use as base name for tags
        tag-sha: true # add git short SHA as Docker tag

    - name: Login to DockerHub
      if: github.event_name != 'pull_request'
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_PASSWORD }}

    - name: Build and Push to Docker Hub
      uses: docker/build-push-action@v1
      with:
        dockerfile: ./Dockerfile
        push: ${{ github.event_name != 'pull_request' }}
        tags: ${{ steps.docker_meta.outputs.tags }}
        labels: ${{ steps.docker_meta.outputs.labels }}

  deploy:
    needs: [docker-build]
    name: Deploying
    runs-on: ubuntu-latest
    steps:
      - name: testing second job
        run: |
          echo "Deploying app"