name: Python application

on:
  push:
    branches:
      - features
  pull_request:
    branches:
      - main

jobs:

  test:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:12.0-alpine
        env:
          POSTGRES_USER: test
          POSTGRES_PASSWORD: test
          POSTGRES_DB: test
        ports:
          - "5432:5432"

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python 3.8.5
      uses: actions/setup-python@v2
      with:
        python-version: 3.8.5

    - name: Install python dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

    - name: Running django tests
      run: |
        cd src
        python manage.py test
      env:
        DB_NAME: test
        DB_USER: test
        DB_PASS: test
        DB_HOST: 127.0.0.1
        DB_PORT: 5432

    - name: Lint with flake8
      run: |
        cd src
        flake8

  docker-images:
    needs:
      - test
    runs-on: ubuntu-latest
    steps:
    - name: testing second job
      run: |
        echo "Hello docker"